NewKTG/NewKTG/Areas/Setup/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Activity : Location
	{
		public int id { get; set; }
		public string Description { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Cities.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Cities
	{
		[Key]
		public int CityID { get; set; }
		public string CityName { get; set; }
		public string State { get; set; }
		public virtual ICollection<Shul> Shuls { get; set; } = new HashSet<Shul>();
		public virtual ICollection<Activity> Activities { get; set; } = new HashSet<Activity>();
		public virtual ICollection<Hotel> Hotels { get; set; } = new HashSet<Hotel>();
		public virtual ICollection<FoodEstablishment> FoodEstablishments { get; set; } = new HashSet<FoodEstablishment>();
		public virtual Coordinates Coordinates { get; set; }

	}
}

NewKTG/NewKTG/Areas/Setup/Models/Coordinates.cs
using Geocoding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace KTG.Areas.Setup.Models
{

	public class Coordinates
	{
		public int ID { get; set; }
		public double Longitude { get; set; }
		public double Latitude { get; set; }
		
		public async Task<Coordinates> GetCoordinates(string address, string city, string state, string zip)
		{
			IGeocoder geocoder = Geocoder.Instance.IGeo;
			IEnumerable<Address> addresses = await geocoder.GeocodeAsync(string.Format("{0} {1}, {2} {3}", address, city, state, zip));
			Coordinates c = new Coordinates
			{
				Longitude = addresses.First().Coordinates.Longitude,
				Latitude = addresses.First().Coordinates.Latitude
			};
			return c;
		}

	
	}
}

NewKTG/NewKTG/Areas/Setup/Models/FoodEstablishment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Models
{
	public class FoodEstablishment : Location
	{
		public int ID { get; set; }
		public string Type { get; set; }
		public virtual Hechsher Hechsher { get; set; }
		public string Category { get; set; }
		public string Description { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Geocoder.cs
using Geocoding;
using Geocoding.Google;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public sealed class Geocoder
	{
		private static volatile Geocoder instance;
		private static object syncRoot = new object();

		public static Geocoder Instance
		{
			get
			{
				if (instance == null)
				{
					lock (syncRoot)
					{
						if (instance == null)
							instance = new Geocoder();
					}
				}
				return instance;
			}
		}

		public static void Init()
		{
			Geocoder geocoder = Instance;
			Instance.IGeo = new GoogleGeocoder() { ApiKey = "AIzaSyCuokH7vVIf-FyYXtPXz8EPKnQ7bafv1Ww" };
		}

		public IGeocoder IGeo { get; set; }

	}
}

NewKTG/NewKTG/Areas/Setup/Models/Hechsher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Hechsher
	{
		public int id { get; set; }
		public string Name { get; set; }
		[DisplayName("Rabbi(s)")]
		public string Rabbis { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string State { get; set; }
		public string Zip { get; set; }
		public string Phone { get; set; }
		public string Email { get; set; }
		public string WebSite { get; set; }
		public bool CrcApproved { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Hotel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Hotel : Location
	{
		public int HotelID { get; set; }
		public decimal Stars { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public abstract class Location
	{
		public string Name { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string State { get; set; }
		public string Zip { get; set; }
		public string Country { get; set; }
		[Phone]
		public string Phone { get; set; }
		[EmailAddress]
		public string Email { get; set; }
		public string Website { get; set; }
		public virtual Cities IDCity { get; set; }
		public virtual Coordinates Coordinates { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Shul.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Shul : Location
	{
		public int ShulID { get; set; }
		public string Rabbi { get; set; }
		public string Nusach { get; set; }
		public virtual ICollection<Zman> Zmanim { get; set; } = new HashSet<Zman>();
	}
}

NewKTG/NewKTG/Areas/Setup/Models/Zman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Zman
	{
		public int ID { get; set; }
		public virtual Shul Shul { get; set; }
		//[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:HH:mm}")]
		public string Time { get; set; }
		[DisplayName("Custom Time")]
		public string OtherTime { get; set; }
		public string Days { get; set; }
		public string Prayer { get; set; }

	}
}

NewKTG/NewKTG/Areas/Setup/ViewModels/HotelSetupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.ViewModels
{
	public class HotelSetupViewModel
	{
		public SetupViewModel svm = new SetupViewModel();
		public string Name { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string State { get; set; }
		public string Zip { get; set; }
		public string Country { get; set; }
		[Phone]
		public string Phone { get; set; }
		[EmailAddress]
		public string Email { get; set; }
		public string Website { get; set; }
		public decimal Stars { get; set; }
		public int CityCode { get; set; }
	}
}

NewKTG/NewKTG/Areas/Setup/ViewModels/ShulSetupViewModel.cs
using KTG.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.ViewModels
{
	public class ShulSetupViewModel
	{
		public SetupViewModel svm = new SetupViewModel();
		public string Name { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string State { get; set; }
		public string Zip { get; set; }
		public string Country { get; set; }
		[Phone]
		public string Phone { get; set; }
		[EmailAddress]
		public string Email { get; set; }
		public string Website { get; set; }
		public string Rabbi { get; set; }
		public string Nusach { get; set; }
		public string OtherNusach { get; set; }
		public int CityCode { get; set; }

		public SelectList NusachSelector()
		{
			List<SelectListItem> lst = new List<SelectListItem>()
				{
					new SelectListItem() { Text="Ashkenaz", Value="Ashkenaz"},
					new SelectListItem() { Text="Sefard", Value="Sefard"},
					new SelectListItem() { Text="Edut Hamizrach", Value="Edut Hamizrach"},
					new SelectListItem() { Text="Ari", Value="Ari"},
					new SelectListItem() { Text="Other", Value="Other"}
			};
			return new SelectList(lst, "Value", "Text");
		}
	}
}

NewKTG/NewKTG/Areas/Setup/ViewModels/ShulViewModel.cs
using KTG.Areas.Setup.Models;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.ViewModels
{
	public class ShulViewModel
	{
		public Shul Shul { get; set; }
		public List<Zman> Zmanim { get; set; }
		public ZmanimViewModel ZVM { get; set; }
		public Zman Z = new Zman();
	}
}

NewKTG/NewKTG/Areas/Setup/Controllers/ActivtyController.cs
using Geocoding;
using KTG.Areas.Setup.Models;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Controllers
{
	public class ActivityController : Controller
	{
		Db db = new Db();
		// GET: Activty
		public ActionResult Index(int CityId = 0)
		{
			if (CityId == 0)
				return View(db.Activities.ToList());
			else
				return View(db.Activities.Where(f => f.IDCity.CityID == CityId));
		}

		public ActionResult AddActivity(int id)
		{
			Activity a = new Activity
			{
				IDCity = db.Cities.Find(id)
			};
			return View(a);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async System.Threading.Tasks.Task<ActionResult> AddActivity(Activity a)
		{
		  	a.IDCity = db.Cities.Find(a.IDCity.CityID);
			a.Coordinates = await new Coordinates().GetCoordinates(a.Address, a.City, a.State, a.Zip);
			db.Activities.Add(a);
			db.SaveChanges();
			return RedirectToAction("Index", new { id = a.IDCity.CityID });
		}

		public ActionResult Edit(int id)
		{
			return View(db.Activities.Find(id));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Activity a)
		{
			db.Entry(a).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index", new { id = a.IDCity.CityID });
		}

		public ActionResult Details(int id)
		{
			return View(db.Activities.Find(id));
		}

		public ActionResult Delete(int id)
		{
			Activity a = db.Activities.Find(id);
			int cityID = a.IDCity.CityID;
			db.Activities.Remove(db.Activities.Find(id));
			db.SaveChanges();
			return RedirectToAction("index", new { id = cityID });
		}
    }
}

NewKTG/NewKTG/Areas/Setup/Controllers/FoodEstablishmentController.cs
using KTG.Areas.Setup.Models;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Controllers
{
    public class FoodEstablishmentController : Controller
    {
		Db db = new Db();
        // GET: FoodEstablishment
        public ActionResult Index(int id)
        {
			if (id == null || id == 0)
				return View(db.FoodEstablishments.ToList());
			else
				return View(db.FoodEstablishments.Where(f => f.IDCity.CityID == id));
        }

		public ActionResult AddNew(int id)
		{
			FoodEstablishment f = new FoodEstablishment();
			f.IDCity = db.Cities.Find(id);
			return View(f);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddNew(FoodEstablishment F)
		{
			F.IDCity = db.Cities.Find(F.IDCity.CityID);
			F.Hechsher = db.Hechshers.Find(F.Hechsher.id);
			db.FoodEstablishments.Add(F);
			db.SaveChanges();
			return RedirectToAction("Index", new { id = F.IDCity.CityID });
		}

		public ActionResult Edit(int id)
		{
			FoodEstablishment f = db.FoodEstablishments.Find(id);
			return View(f);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(FoodEstablishment f)
		{
			db.Entry(f).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index", new { id = f.IDCity.CityID });
		}

		public ActionResult Details(int id)
		{
			var model = db.FoodEstablishments.Find(id);
			return View(db.FoodEstablishments.Find(id));
		}

		public ActionResult Delete(int id)
		{
			var del = db.FoodEstablishments.Find(id);
			var cid = del.IDCity.CityID;
			db.FoodEstablishments.Remove(del);
			db.SaveChanges();
			return RedirectToAction("Index", new { id = cid });
		}
    }
}

NewKTG/NewKTG/Areas/Setup/Controllers/HechsherController.cs
using KTG.Areas.Setup.Models;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Controllers
{
    public class HechsherController : Controller
    {
		Db db = new Db();
        // GET: Hechsher
        public ActionResult Index()
        {
			List<Hechsher> list = new List<Hechsher>();
			var l = db.Hechshers.OrderBy(h => h.Name).ToList();
			if (l.Count > 0)
				list = l;
			return View(list);
        }

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Hechsher h)
		{
			db.Hechshers.Add(h);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Edit(int id)
		{
			return View(db.Hechshers.Find(id));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Activity a)
		{
			db.Entry(a).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		public ActionResult Details(int id)
		{
			return View(db.Hechshers.Find(id));
		}

		public ActionResult Delete(int id)
		{
			Hechsher h = db.Hechshers.Find(id);
			db.Hechshers.Remove(h);
			db.SaveChanges();
			return RedirectToAction("index");
		}
	}
}

NewKTG/NewKTG/Areas/Setup/Controllers/HotelController.cs
using KTG.Areas.Setup.Models;
using KTG.Areas.Setup.ViewModels;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Controllers
{
    public class HotelController : Controller
    {
		Db db = new Db();
		public ActionResult AddHotel(int id)
		{
			HotelSetupViewModel model = new HotelSetupViewModel();
			model.CityCode = id;
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddHotel(HotelSetupViewModel model)
		{
			Hotel hotel = new Hotel()
			{
				Name = model.Name,
				Address = model.Address,
				City = model.City,
				State = model.State,
				Zip = model.Zip,
				IDCity = db.Cities.Find(model.CityCode),
				Website = model.Website,
				Phone = model.Phone,
				Stars = model.Stars,
				Email = model.Email
			};
			db.Hotels.Add(hotel);
			db.SaveChanges();
			return RedirectToAction("AllHotels", new { id = model.CityCode });
		}

		public ActionResult AllHotels(int id)
		{
			var HotelList = db.Hotels.Where(h => h.IDCity.CityID == id).ToList();
			if (HotelList.Count() == 0)
			{
				Hotel h = new Hotel()
				{
					IDCity = db.Cities.Find(id)
				};
				HotelList.Add(h);
			}
			return View(HotelList);
		}

		public ActionResult EditHotel(int id)
		{
			Hotel hotel = db.Hotels.Find(id);
			return View(hotel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditHotel(Hotel hotel)
		{
			Hotel h = db.Hotels.Find(hotel.HotelID);
			h.Address = hotel.Address;
			h.City = hotel.City;
			h.IDCity = hotel.IDCity;
			h.Country = hotel.Country;
			h.Email = hotel.Email;
			h.Name = hotel.Name;
			h.Phone = hotel.Phone;
			h.Stars = hotel.Stars;
			h.Stars = hotel.Stars;
			h.Website = hotel.Website;
			h.Zip = hotel.Zip;
			db.SaveChanges();
			return RedirectToAction("AllHotels", new { id = hotel.IDCity.CityID });
		}

		public ActionResult Delete(int id)
		{
			Hotel h = db.Hotels.Find(id);
			int cityID = h.IDCity.CityID;
			db.Hotels.Remove(db.Hotels.Find(id));
			db.SaveChanges();
			return RedirectToAction("AllHotels", new { id = cityID });

		}

		public ActionResult Details(int id)
		{
			return View(db.Hotels.Find(id));
		}

	}
}

NewKTG/NewKTG/Areas/Setup/Controllers/SetupController.cs
using KTG.Areas.Setup.Models;
using KTG.Areas.Setup.ViewModels;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Controllers
{
	public class SetupController : Controller
	{
		Db db = new Db();
		// GET: Setup
		public ActionResult Index()
		{
			SetupViewModel model = new SetupViewModel();
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Index(SetupViewModel model)
		{
			Db db = new Db();
			model.Cities = db.Cities.Where(c => c.State == model.State).OrderBy(c=>c.CityName).ToList();
			return RedirectToAction("CitySetup", new { model = model });
		}

		public ActionResult CitySetup(SetupViewModel model = null, string state = "")
		{
			if (model != null)
			{
				if (model.State != null)
				{
					var CheckForCities = db.Cities.Where(c => c.State == model.State).ToList();
					if (CheckForCities.Count() == 0)
					{
						model.NoCities = true;
					}
					else
					{
						model.Cities = CheckForCities;
					}
					return View(model);
				}
			}
			if (state != null)
			{
				var cities = db.Cities.Where(c => c.State == state);
				if (cities.Count() == 0)
				{
					model.NoCities = true;
				}
				else
				{
					model.Cities = cities.ToList();
				}
				return View(model);
			}
			else
				return RedirectToAction("Index");

		}

		[HttpPost]
		public ActionResult AddCity(SetupViewModel model)
		{
			Db db = new Db();
			Cities newCity = new Cities()
			{
				CityName = model.CityName,
				State = model.State
			};
			db.Cities.Add(newCity);
			db.SaveChanges();
			return RedirectToAction("CitySetup", model);

		}

		

		

		
	}
}

NewKTG/NewKTG/Areas/Setup/Views/Setup/AddZman.cshtml
@model KTG.Areas.Setup.ViewModels.ZmanimViewModel

@{
	ViewBag.Title = "Add Zman";
}

<h2>Add Zman</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Zman</h4>
		<hr />
		@Html.HiddenFor(m => m.ShulID)
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control time" } })
				@Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.OtherTime, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.OtherTime, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.OtherTime, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.Days, Model.DaySelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Prayer, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.Prayer, Model.PrayerSelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Prayer, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css" type="text/css" />
	<script src="https://code.jquery.com/jquery-2.2.2.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.css" type="text/css" />
	<script>

		$(document).ready(function () {
			$(".time").timepicker();
		});
	</script>


}

NewKTG/NewKTG/Areas/Setup/Views/Setup/CitySetup.cshtml
@model KTG.Areas.Setup.ViewModels.SetupViewModel
@{
	ViewBag.Title = "City Setup";
}

<h2>@Model.State</h2>
<div class="form-horizontal">
	@Html.ActionLink("Manage Hechsher", "Index", "Hechsher")
	@if (Model.Cities != null)
	{
		<div class="form-group">
			@Html.LabelFor(m => Model.Cities, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.Cities, Model.GetCitiesSelector(), "Select City", new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Cities, "", new { @class = "text-danger" })
			</div>
		</div>
	}

	@using (Html.BeginForm("AddCity", "Setup"))
	{
		<h3>Add City</h3>
		@Html.HiddenFor(m => Model.State)
		<div class="form-group">
			@Html.LabelFor(m => Model.CityName, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextBoxFor(model => model.CityName, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
				<button style="display: inline-block" type="submit" value="Go">Add</button>
			</div>
		</div>

	}
</div>
<div  id="AddDivs" class="form-horizontal"
	<div id="UpdateCity" class="form-group">
		<div id="CityNameDiv"></div>
		<div id="CityButtons"></div>
	</div>
</div>
@section scripts{
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")
	<script>
		$(document).ready(function () {
			var id = $("#Cities option:selected").val();
			if (id != "")
				LoadAll(id);
		});
		$("#Cities").change(function () {
			$("#CityNameDiv").empty();
			$("#CityButtons").empty();
			if ($("#Cities").val() != "") {
				var id = $("#Cities option:selected").val();
				LoadAll(id);
			}
		});
		function LoadAll(id) {
			var header = '<h3>' + $("#Cities option:selected").text() + '</h3>';
			var buttons = '<a href="/Setup/Shul/AddShul/?id=' + id + '" class="btn btn-default">Add Shul</a>' +
				'<a href="/Setup/Hotel/AddHotel/?id=' + id + '" class="btn btn-default">Add Hotel</a>' +
				'<a href="/Setup/FoodEstablishment/AddNew/?id=' + id + '" class="btn btn-default">Add Food Est</a>' +
				'<a href="/Setup/Activity/AddActivity/?id=' + id + '" class="btn btn-default">Add Activities</a>' +
				'<br/>' +
				'<a href="/Setup/Shul/AllShuls/?id=' + id + '" class="btn btn-default">Shuls</a>' +
				'<a href="/Setup/Hotel/AllHotels/?id=' + id + '" class="btn btn-default">Hotels</a>' +
				'<a href="/Setup/FoodEstablishment/Index/?id=' + id + '" class="btn btn-default">All Food</a>' +
				'<a href="/Setup/Activity/Index/?id=' + id + '" class="btn btn-default">Activities</a>';
			$("#CityNameDiv").append(header);
			$("#CityButtons").append(buttons);
		}
	</script>

}

NewKTG/NewKTG/Areas/Setup/Views/Setup/Index.cshtml
@model KTG.Areas.Setup.ViewModels.SetupViewModel
@{
	ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("CitySetup", "Setup"))
{
	<div class="form-group">
		@Html.LabelFor(m => Model.State, new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownListFor(model => model.State, Model.GetStateSelector(), "Select State", new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
		</div>
	</div>
	<button type="submit" value="Go">Go</button>
}