NewKTG/NewKTG/Areas/Setup/Models/Shul.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.Models
{
	public class Shul : Location
	{
		public int ShulID { get; set; }
		public string Rabbi { get; set; }
		public string Nusach { get; set; }
		public virtual ICollection<Zman> Zmanim { get; set; } = new HashSet<Zman>();
	}
}

NewKTG/NewKTG/Areas/Setup/ViewModels/ShulViewModel.cs
using KTG.Areas.Setup.Models;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KTG.Areas.Setup.ViewModels
{
	public class ShulViewModel
	{
		public Shul Shul { get; set; }
		public List<Zman> Zmanim { get; set; }
		public ZmanimViewModel ZVM { get; set; }
		public Zman Z = new Zman();
	}
}

NewKTG/NewKTG/Areas/Setup/Controllers/ShulController.cs
using KTG.Areas.Setup.Models;
using KTG.Areas.Setup.ViewModels;
using KTG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTG.Areas.Setup.Controllers
{
    public class ShulController : Controller
    {
		Db db = new Db();
		public ActionResult AddShul(int id)
		{
			ShulSetupViewModel shul = new ShulSetupViewModel();
			shul.CityCode = db.Cities.Find(id).CityID;
			return View(shul);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddShul(ShulSetupViewModel model)
		{
			Shul shul = new Shul()
			{
				Name = model.Name,
				Address = model.Address,
				City = model.City,
				State = model.State,
				Zip = model.Zip,
				IDCity = db.Cities.Find(model.CityCode),
				Website = model.Website,
				Phone = model.Phone,
				Rabbi = model.Rabbi,
				Email = model.Email
			};
			if (model.OtherNusach == null)
				shul.Nusach = model.Nusach;
			else
				shul.Nusach = model.OtherNusach;
			db.Shuls.Add(shul);
			db.SaveChanges();
			return RedirectToAction("AllShuls", new { id = model.CityCode });
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditShul(Shul shul)
		{
			db.Entry(shul).State = System.Data.Entity.EntityState.Modified;
			db.SaveChanges();
			return RedirectToAction("AllShuls", new { id = shul.IDCity.CityID });
		}

		public ActionResult EditShul(int id)
		{
			Shul shul = db.Shuls.Find(id);
			return View(shul);
		}

		public ActionResult DeleteShul(int id)
		{
			Shul s = db.Shuls.Find(id);
			int CityID = s.IDCity.CityID;
			db.Shuls.Remove(s);
			db.SaveChanges();
			return RedirectToAction("AllShuls", new { id = CityID});
		}

		public ActionResult AllShuls(int id)
		{
			var ShulList = db.Shuls.Where(s => s.IDCity.CityID == id).ToList();
			if (ShulList.Count() == 0)
			{
				Shul s = new Shul()
				{
					IDCity = db.Cities.Find(id)
				};
				ShulList.Add(s);
			}
			return View(ShulList);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddZman(ShulViewModel model)
		{
			Shul shul = db.Shuls.Find(model.ZVM.ShulID);
			Zman zman = new Zman();
			zman.Days = model.ZVM.Days;
			if (model.ZVM.Time != null)
				zman.Time = model.ZVM.Time;
			else
				zman.OtherTime = model.ZVM.OtherTime;
			zman.Prayer = model.ZVM.Prayer;

			shul.Zmanim.Add(zman);
			db.SaveChanges();
			return RedirectToAction("ShulView", new { model.ZVM.ShulID });
		}

		public ActionResult ShulView(int ShulID)
		{
			ShulViewModel model = new ShulViewModel();
			model.ZVM = new ZmanimViewModel()
			{
				ShulID = ShulID
			};
			model.Shul = db.Shuls.Find(ShulID);
			//model.Zmanim = model.Shul.Zmanim.ToList() ?? null;
			return View(model);
		}

		public ActionResult DeleteZman(int id)
		{
			Zman z = db.Zmanim.Find(id);
			int ShulID = z.Shul.ShulID;
			db.Zmanim.Remove(z);
			db.SaveChanges();
			return RedirectToAction("ShulView", new { ShulID = ShulID });
		}
	}
}

NewKTG/NewKTG/Areas/Setup/Views/Shul/AddShul.cshtml
@model KTG.Areas.Setup.ViewModels.ShulSetupViewModel

@{
	ViewBag.Title = "AddShul";
}

<h2>Add Shul</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Shul</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.State, Model.svm.GetStateSelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
			</div>
		</div>

		@*<div class="form-group">
				@Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
				</div>
			</div>*@

		<div class="form-group">
			@Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Rabbi, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Rabbi, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Rabbi, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(model => model.Nusach, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.Nusach, Model.NusachSelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.Nusach, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="form-group" id="OtherNusachDiv" style="display:none">
			@Html.LabelFor(model => model.OtherNusach, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.OtherNusach, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.OtherNusach, "", new { @class = "text-danger" })
			</div>
		</div>
		@Html.HiddenFor(m => m.CityCode);
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")
	<script>
		$("#Nusach").change(function () {
			if ($("#Nusach").val() == "Other") {  
				$("#OtherNusachDiv").show();
			}
			else {
				$("#OtherNusachDiv").hide();
			}
		})
	</script>

}

NewKTG/NewKTG/Areas/Setup/Views/Shul/AllShuls.cshtml
@model IEnumerable<KTG.Areas.Setup.Models.Shul>

@{
    ViewBag.Title = "All Shuls";
}

<h2>All Shuls</h2>

<p>
	@Html.ActionLink("Add New", "AddShul", new { id = Model.Select(m => m.IDCity.CityID).First() }, new { @class = "btn btn-default" })
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Address)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.City)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.State)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Zip)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Country)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Phone)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Email)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Website)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Rabbi)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Nusach)
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.Name)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Address)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.City)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.State)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Zip)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Country)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Phone)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Email)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Website)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Rabbi)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Nusach)
		</td>
		<td>
			@Html.ActionLink("Edit", "EditShul", new { id = item.ShulID }) |
			@Html.ActionLink("Details", "ShulView", new { shulid = item.ShulID }) |
			@Html.ActionLink("Delete", "DeleteShul", new { id = item.ShulID })
		</td>
	</tr>
}

</table>

NewKTG/NewKTG/Areas/Setup/Views/Shul/EditShul.cshtml
@model KTG.Areas.Setup.Models.Shul

@{
    ViewBag.Title = "EditShul";
}

<h2>EditShul</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shul</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShulID)
		@Html.HiddenFor(model => model.IDCity.CityID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
		@{ KTG.ViewModels.SetupViewModel svm = new KTG.Areas.Setup.ViewModels.SetupViewModel();}
		<div class="form-group">
			@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.State, svm.GetStateSelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rabbi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rabbi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rabbi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nusach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nusach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nusach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NewKTG/NewKTG/Areas/Setup/Views/Shul/ShulView.cshtml
@model KTG.Areas.Setup.ViewModels.ShulViewModel
@{
	ViewBag.Title = "ShulView";
}

<h2>Shul #@Model.Shul.ShulID</h2>
@Html.ActionLink("Back to List", "AllShuls", new { id = Model.Shul.IDCity.CityID })
<hr />
<h3>@Model.Shul.Name</h3>
<p>@Model.Shul.Address</p>
<p>
	@Model.Shul.City ,
	@Model.Shul.State
</p>
<p>@Model.Shul.Zip</p>
<p>@Model.Shul.Phone</p>
<p>@Model.Shul.Email</p>
<p>@Model.Shul.Website</p>
<p><strong>Rabbi </strong>@Model.Shul.Rabbi</p>
<p>@Model.Shul.Nusach</p>
<hr />

@Html.ActionLink("Edit", "EditShul", new { @class = "btn btn-default",  id = Model.Shul.ShulID }) |
@Html.ActionLink("Delete", "Delete", new {  @class = "btn btn-default", id = Model.Shul.ShulID })
<h3>Zmanim</h3>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Z.Days)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Z.Prayer)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Z.Time)
		</th>

	</tr>
	@if (Model.Shul.Zmanim != null)
	{
		foreach (var item in Model.Shul.Zmanim)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Days)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Prayer)
				</td>
				@if (item.Time != null)
				{
					<td>
						@Html.DisplayFor(modelItem => item.Time)
					</td>
				}
				else
				{
					<td>
						@Html.DisplayFor(modelItem => item.OtherTime)
					</td>
				}

				<td>
					@Html.ActionLink("Delete", "DeleteZman", new { id = item.ID })
				</td>
			</tr>
		}
	}
</table>

@using (Html.BeginForm("AddZman","Shul", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Zman</h4>
		<hr />
		@Html.HiddenFor(m => m.ZVM.ShulID)
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.ZVM.Time, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.TextBoxFor(model => model.ZVM.Time, new { @class = "form-control time" })
				@Html.ValidationMessageFor(model => model.ZVM.Time, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ZVM.OtherTime, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.ZVM.OtherTime, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.ZVM.OtherTime, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ZVM.Days, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.ZVM.Days, Model.ZVM.DaySelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.ZVM.Days, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.ZVM.Prayer, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.ZVM.Prayer, Model.ZVM.PrayerSelector(), new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.ZVM.Prayer, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}


@section scripts{
	<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css" type="text/css" />
	<script src="https://code.jquery.com/jquery-2.2.2.js"></script>
	<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.css" type="text/css" />
	<script>

		$(document).ready(function () {
			$(".time").timepicker();
		});
	</script>


}